version: '3.9'

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${DOCKER_VOLUMES_PATH}/jellyfin:/config
      - ${DOCKER_VOLUMES_PATH}/media/tv:/data/tv
      - ${DOCKER_VOLUMES_PATH}/media/movies:/data/movies
      - ${DOCKER_VOLUMES_PATH}/media/music:/data/music
      - ${DOCKER_VOLUMES_PATH}/media/youtube:/data/youtube
      - ${DOCKER_VOLUMES_PATH}/media/downloads:/data/downloads
    ports:
      - "${JELLYFIN_PORT:-8096}:8096"
      - "${JELLYFIN_HTTPS_PORT:-8920}:8920"
      - "${JELLYFIN_DLNA_PORT:-1900}:1900/udp"
      - "${JELLYFIN_DISCOVERY_PORT:-7359}:7359/udp"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
